### ISSUE TITLE
ESP8266 only works with 20000Hz

### ISSUE THREAD

**Issue by jopsi** [cyrusbuilt/CyMCP23016#2]
Hi, 
thanks for your lib. It works well with ESP32 and now also with ESP8266. Needed to modify Wire.setClock(200000); to Wire.setClock(20000);
Maybe also a good hint is that SDA and SCL need a pull-up the VCC (3.3V) by 2.2K resistors
BR
jopsi

**Comment by sirpete83** [comment]
Hi jopsi,
today I tested this lib with the ESP32, I had the same problems that the communication was only possible with low speed. 20000 Hz. The problem is not the speed! In my case I could use the maximum speed of 400000 Hz by inserting a delay after the Wire.begin(); I do not belive the position of the delay is that important, but if you check the datasheet you have to wait at least 75 ms before the first transmission to the MCP23016. if you do so you can use full speed. 
by selecting a lower speed, the reset time of the MCP is reached because of the lower speed.

**Comment by jopsi** [comment]
Hi SirPete83,
vielen Dank für Deinen Hinweis. Ich habe das projekt wegen anderer Gründen aufgegeben. Werde aber mal schauen ob ich das Perfboard mit dem MCP23016 noch reaktiviert bekomme und dann mal den delay in das setup einbaue.
